export enum ActionType {
  CREATE_PROJECT = "CREATE_PROJECT",
  DELETE_PROJECT = "DELETE_PROJECT",
  LOAD_PROJECT_DATA = "LOAD_PROJECT_DATA",

  // Global
  FETCHING = "FETCHING",
  ERROR = "ERROR",
  SUCCESS = "SUCCESS"
}
